services:
  satisfactory-server:
    container_name: 'satisfactory-monitor'
    hostname: 'satisfactory-monitor'
    build: 
      context: './'
    ports:
      - '8888:8888/tcp'
    volumes:
      - './config:/config'
    env_file: 
      - '.env'
    restart: unless-stopped
