services:
  satisfactory-server:
    container_name: 'satisfactory-monitor'
    hostname: 'satisfactory-monitor'
    build: 
      context: './'
    ports:
      - '8888:8888/tcp'
    volumes:
      - '/opt/docker/satisfactory-server/config/saved/server:/saves'
      - './sslcert:/sslcert'
    env_file: 
      - '.env'
    restart: unless-stopped
